### ISSUE TITLE
NO BUILD FOLDER #ROOKIE MISTAKE

### ISSUE THREAD

**Issue by akshats911** [ZODIAC3K/Dockerize-CLI#1]

**Comment by ZODIAC3K** [comment]
Hey, I appreciate your feedback! I’ve added Webpack to build the project, which will now ensure all required files (including fonts) are bundled correctly into a dist folder. This fixes the missing build folder issue. Thanks for pointing that out!

Feel free to check out the latest version, and let me know if you encounter any more issues.
